
const MainPageTypes={
    ON_FETCH_MOVIE: 'ON_FETCH_MOVIE',
    ON_FETCH_MOVIE_START: 'ON_FETCH_MOVIE_START',
    ON_FETCH_MOVIE_SUCCESS: 'ON_FETCH_MOVIE_SUCCESS',
    ON_FETCH_MOVIE_FAILURE: 'ON_FETCH_MOVIE_FAILURE',
    ON_SUBMIT: 'ON_SUBMIT'
}
export default MainPageTypes;
