const AutoSuggestTypes = {
    UPDATE_INPUT_VALUE: 'UPDATE_INPUT_VALUE',
    LOAD_SUGGESTIONS_START: 'LOAD_SUGGESTIONS_START',
    LOAD_SUGGESTIONS_FETCH: 'LOAD_SUGGESTIONS_FETCH',
    ON_CLEAR_SUGGESTIONS:'ON_CLEAR_SUGGESTIONS',
    ON_GET_SUGGESTION_VALUE: 'ON_GET_SUGGESTION_VALUE',
    ON_RENDER_SUGGESTION: 'ON_RENDER_SUGGESTION',
    // ON_SELECTED: 'ON_SELECTED'
};

export default AutoSuggestTypes;